# golangci-lint config for Go library. High-signal linters only; no formatting/import order.
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  build-tags: []

output:
  formats:
    text: {}

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions: []
    govet:
      enable-all: true
      disable:
        - fieldalignment
  exclusions:
    paths:
      - vendor
      - '.*\.gen\.go$'
      - '.*_string\.go$'
      - '.*\.pb\.go$'
    rules:
      - path: _test\.go
        linters:
          - errcheck
        text: "Close"
      - path: _test\.go
        linters:
          - unused
      - path: _test\.go
        linters:
          - ineffassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
